server:
  servlet:
    context-path: /crud
spring:
  thymeleaf:
    cache: false

  messages:
    basename: i18n.login
  mvc:
    date-format: yyyy-MM-dd HH:mm

    hiddenmethod:
      filter:
        enabled: true